server:
  port: 8080
spring:
  application:
    name: spring-multitenancy
  datasource:
    url: jdbc:postgresql://localhost:5432/rls_lab
    username: app_user
    password: app_password
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/rls_lab
    user: migration_user
    password: migration_password



