server:
  port: 8080
spring:
  application:
    name: spring-multitenancy
  datasource:
    url: jdbc:postgresql://localhost:5432/rls_lab
    username: migration_user
    password: migration_password

  flyway:
    enabled: true


